### ISSUE TITLE
Diffusion inference with precomputed latents

### ISSUE THREAD

**Issue by alhojel** [OpenEarthLab/CasCast#1]
These are the outputs I'm getting... Does this look right?
<img width="742" alt="Screenshot 2024-06-12 at 3 19 27 PM" src="https://github.com/OpenEarthLab/CasCast/assets/51961972/0b31d83e-4716-4eb0-98d7-ef96e4bed018">

**Comment by alhojel** [comment]
![pixel_step320_time0](https://github.com/OpenEarthLab/CasCast/assets/51961972/45e604fa-dc79-4786-b0b3-23b9b616acea)
Another one for example. No change from tstep 0 to tstep 320

**Comment by jasong-ovo** [comment]
have you loaded the pretrained model correctly?

**Comment by jasong-ovo** [comment]
At least, the picture of target should be the same as the ground truth data...
