### ISSUE TITLE
X0: Xt as a condition in the diffusion process is implemented

### ISSUE THREAD

**Issue by MingjianFu** [OpenEarthLab/CasCast#2]
May I ask where the process of introducing X0: Xt as a condition in the diffusion process is implemented? I don't seem to have found it

**Comment by jasong-ovo** [comment]
It is implemented by the CrossBlock in networks/Casformer.py . In this version, we don't use CrossBlock, as the gain obtained by introducing X0: Xt is not significant. We think postprocessing is enough.
