### ISSUE TITLE
srun: unrecognized option '--quotatype=auto'

### ISSUE THREAD

**Issue by plaovem** [OpenEarthLab/CasCast#3]
Hello,
I try to run the command: "bash ./scripts/eval_diffusion_infer.sh", but it shows that:
srun: unrecognized option '--quotatype=auto'

**Comment by jasong-ovo** [comment]
Thanks for your attention. This codebase is adjusted to SLURM platform. If you use this platform and has this problem, you could try to change "auto" to "reserved" or "spot".
